version: '3.7'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"   # Expose Nextcloud on port 8080 (you can change the port if needed)
    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_config:/config
    environment:
      - MYSQL_PASSWORD=mysecretpassword  # Set the MySQL password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Root password for MariaDB
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=mysecretpassword  # User password for the Nextcloud database
    volumes:
      - db_data:/var/lib/mysql

volumes:
  nextcloud_data:
  nextcloud_config:
  db_data:
